/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! A runtime RMS gRPC mock.
//!
//! The RMS API is served by an external service that drives real rack
//! hardware. Simulated hardware has no such service, so rack workflows that
//! call RMS cannot run against a simulated fleet. This crate implements the
//! RMS gRPC surface directly, using the server bindings generated by
//! `librms`, so a normally configured NICo process can talk to it over the
//! wire without knowing it is not the real thing.
//!
//! The mock is deliberately independent of machine-a-tron: it owns
//! protocol behaviour only, and reads hardware state through a trait its host
//! implements. That boundary is what lets a future multi-pod gateway supply a
//! fan-out inventory instead of a local one.

mod config;
mod inventory;
mod resolve;
mod router;
mod service_v1;
mod service_v2;

pub use config::RmsMockConfig;
pub use inventory::{RmsInventory, SimNode, SimNodeKind};
/// The V1 protobuf module. Aliased because both service impls refer to it
/// constantly, and because `rack_manager_v2` defines same-named messages that
/// must not be confused with these.
pub(crate) use librms::protos::rack_manager as rms;
/// The V2 protobuf module.
pub(crate) use librms::protos::rack_manager_v2 as rms_v2;
pub use router::router;

/// A simulated RMS instance.
///
/// One mock serves both `RackManager` and `RackManagerV2`; the two are
/// separate gRPC services with separate wire paths, so both must be mounted.
pub struct RmsMock {
    inventory: std::sync::Arc<dyn RmsInventory>,
    config: RmsMockConfig,
}

impl RmsMock {
    pub fn new(inventory: std::sync::Arc<dyn RmsInventory>, config: RmsMockConfig) -> Self {
        Self { inventory, config }
    }
}

/// An [`RmsInventory`] whose node set is fixed at construction.
///
/// Every `nodes()` call returns the same shared snapshot; nothing is rebuilt
/// or observed after construction. Tests and hosts with nothing to report use
/// this in place of a live inventory.
pub struct StaticInventory(std::sync::Arc<[SimNode]>);

impl StaticInventory {
    /// Wraps a fixed set of nodes; the snapshot is shared, never rebuilt.
    pub fn new(nodes: std::sync::Arc<[SimNode]>) -> Self {
        Self(nodes)
    }
}

impl RmsInventory for StaticInventory {
    fn nodes(&self) -> std::sync::Arc<[SimNode]> {
        std::sync::Arc::clone(&self.0)
    }
}
