// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DomainCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainCreateRequest{}

// DomainCreateRequest Request data for creating a tenant-owned DNS Domain at a Site.
type DomainCreateRequest struct {
	// DNS name of the Domain
	Name string `json:"name"`
	// ID of the Site where the Domain will be created
	SiteId string `json:"siteId"`
}

type _DomainCreateRequest DomainCreateRequest

// NewDomainCreateRequest instantiates a new DomainCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainCreateRequest(name string, siteId string) *DomainCreateRequest {
	this := DomainCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	return &this
}

// NewDomainCreateRequestWithDefaults instantiates a new DomainCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainCreateRequestWithDefaults() *DomainCreateRequest {
	this := DomainCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *DomainCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DomainCreateRequest) SetName(v string) {
	o.Name = v
}

// GetSiteId returns the SiteId field value
func (o *DomainCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *DomainCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

func (o DomainCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["siteId"] = o.SiteId
	return toSerialize, nil
}

func (o *DomainCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainCreateRequest := _DomainCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDomainCreateRequest)

	if err != nil {
		return err
	}

	*o = DomainCreateRequest(varDomainCreateRequest)

	return err
}

type NullableDomainCreateRequest struct {
	value *DomainCreateRequest
	isSet bool
}

func (v NullableDomainCreateRequest) Get() *DomainCreateRequest {
	return v.value
}

func (v *NullableDomainCreateRequest) Set(val *DomainCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainCreateRequest(val *DomainCreateRequest) *NullableDomainCreateRequest {
	return &NullableDomainCreateRequest{value: val, isSet: true}
}

func (v NullableDomainCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
