// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DomainUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainUpdateRequest{}

// DomainUpdateRequest Request data for renaming a tenant-owned DNS Domain.
type DomainUpdateRequest struct {
	// New DNS name of the Domain
	Name string `json:"name"`
}

type _DomainUpdateRequest DomainUpdateRequest

// NewDomainUpdateRequest instantiates a new DomainUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainUpdateRequest(name string) *DomainUpdateRequest {
	this := DomainUpdateRequest{}
	this.Name = name
	return &this
}

// NewDomainUpdateRequestWithDefaults instantiates a new DomainUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainUpdateRequestWithDefaults() *DomainUpdateRequest {
	this := DomainUpdateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *DomainUpdateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DomainUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DomainUpdateRequest) SetName(v string) {
	o.Name = v
}

func (o DomainUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *DomainUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainUpdateRequest := _DomainUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDomainUpdateRequest)

	if err != nil {
		return err
	}

	*o = DomainUpdateRequest(varDomainUpdateRequest)

	return err
}

type NullableDomainUpdateRequest struct {
	value *DomainUpdateRequest
	isSet bool
}

func (v NullableDomainUpdateRequest) Get() *DomainUpdateRequest {
	return v.value
}

func (v *NullableDomainUpdateRequest) Set(val *DomainUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainUpdateRequest(val *DomainUpdateRequest) *NullableDomainUpdateRequest {
	return &NullableDomainUpdateRequest{value: val, isSet: true}
}

func (v NullableDomainUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
