// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Subnet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Subnet{}

// Subnet Subnets are network grouping constructs for baremetal machines.
type Subnet struct {
	// Unique UUID v4 identifier for the Subnet
	Id string `json:"id"`
	// Name of the Subnet
	Name string `json:"name"`
	// Description of the Subnet
	Description NullableString `json:"description"`
	// ID of the Site containing the Subnet
	SiteId string `json:"siteId"`
	// ID of the VPC containing the Subnet
	VpcId string `json:"vpcId"`
	// ID of the tenant-owned REST Domain assigned when the Subnet was created
	SubdomainId NullableString `json:"subdomainId"`
	// ID of the Site Controller network segment corresponding to the Subnet
	ControllerNetworkSegmentId NullableString `json:"controllerNetworkSegmentId"`
	// The prefix that gets assigned to the subnet if ipv4 block is chosen
	Ipv4Prefix NullableString `json:"ipv4Prefix"`
	// ID of the derived Tenant IPv4 Block from an Allocation
	Ipv4BlockId NullableString `json:"ipv4BlockId"`
	// Address of the IPv4 gateway in the Subnet
	Ipv4Gateway NullableString `json:"ipv4Gateway"`
	// Prefix of the network in CIDR notation
	Ipv6Prefix NullableString `json:"ipv6Prefix"`
	// ID of the derived Tenant IPv6 Block from an Allocation
	Ipv6BlockId NullableString `json:"ipv6BlockId"`
	// Address of the IPv6 gateway in the Subnet
	Ipv6Gateway NullableString `json:"ipv6Gateway"`
	// Maximum Transmission Unit size in bytes. This property is system-determined and read-only.
	Mtu *int32 `json:"mtu,omitempty"`
	// Max value depends on prefix length of parent IP Block
	PrefixLength int32 `json:"prefixLength"`
	// Routing type of the Subnet
	RoutingType NullableString `json:"routingType"`
	// Status of the Subnet
	Status SubnetStatus `json:"status"`
	// Present when query parameter `includeUsageStats=true`. Prefix and IP usage data is derived by evaluating associated Ethernet interfaces. Each Interface associated with a Subnet consumes a single IP. In addition, one gateway and one broadcast IP address are reserved per Subnet.
	UsageStats *IpBlockUsageStats `json:"usageStats,omitempty"`
	// Chronological status history for the Subnet
	StatusHistory []StatusDetail `json:"statusHistory"`
	// Date/time when the Subnet was created
	Created time.Time `json:"created"`
	// Date/time when the Subnet was last updated
	Updated time.Time `json:"updated"`
}

type _Subnet Subnet

// NewSubnet instantiates a new Subnet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnet(id string, name string, description NullableString, siteId string, vpcId string, subdomainId NullableString, controllerNetworkSegmentId NullableString, ipv4Prefix NullableString, ipv4BlockId NullableString, ipv4Gateway NullableString, ipv6Prefix NullableString, ipv6BlockId NullableString, ipv6Gateway NullableString, prefixLength int32, routingType NullableString, status SubnetStatus, statusHistory []StatusDetail, created time.Time, updated time.Time) *Subnet {
	this := Subnet{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.SiteId = siteId
	this.VpcId = vpcId
	this.SubdomainId = subdomainId
	this.ControllerNetworkSegmentId = controllerNetworkSegmentId
	this.Ipv4Prefix = ipv4Prefix
	this.Ipv4BlockId = ipv4BlockId
	this.Ipv4Gateway = ipv4Gateway
	this.Ipv6Prefix = ipv6Prefix
	this.Ipv6BlockId = ipv6BlockId
	this.Ipv6Gateway = ipv6Gateway
	this.PrefixLength = prefixLength
	this.RoutingType = routingType
	this.Status = status
	this.StatusHistory = statusHistory
	this.Created = created
	this.Updated = updated
	return &this
}

// NewSubnetWithDefaults instantiates a new Subnet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetWithDefaults() *Subnet {
	this := Subnet{}
	return &this
}

// GetId returns the Id field value
func (o *Subnet) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Subnet) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Subnet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Subnet) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *Subnet) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetSiteId returns the SiteId field value
func (o *Subnet) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *Subnet) SetSiteId(v string) {
	o.SiteId = v
}

// GetVpcId returns the VpcId field value
func (o *Subnet) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *Subnet) SetVpcId(v string) {
	o.VpcId = v
}

// GetSubdomainId returns the SubdomainId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetSubdomainId() string {
	if o == nil || o.SubdomainId.Get() == nil {
		var ret string
		return ret
	}

	return *o.SubdomainId.Get()
}

// GetSubdomainIdOk returns a tuple with the SubdomainId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetSubdomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubdomainId.Get(), o.SubdomainId.IsSet()
}

// SetSubdomainId sets field value
func (o *Subnet) SetSubdomainId(v string) {
	o.SubdomainId.Set(&v)
}

// GetControllerNetworkSegmentId returns the ControllerNetworkSegmentId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetControllerNetworkSegmentId() string {
	if o == nil || o.ControllerNetworkSegmentId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ControllerNetworkSegmentId.Get()
}

// GetControllerNetworkSegmentIdOk returns a tuple with the ControllerNetworkSegmentId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetControllerNetworkSegmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ControllerNetworkSegmentId.Get(), o.ControllerNetworkSegmentId.IsSet()
}

// SetControllerNetworkSegmentId sets field value
func (o *Subnet) SetControllerNetworkSegmentId(v string) {
	o.ControllerNetworkSegmentId.Set(&v)
}

// GetIpv4Prefix returns the Ipv4Prefix field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetIpv4Prefix() string {
	if o == nil || o.Ipv4Prefix.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ipv4Prefix.Get()
}

// GetIpv4PrefixOk returns a tuple with the Ipv4Prefix field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetIpv4PrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipv4Prefix.Get(), o.Ipv4Prefix.IsSet()
}

// SetIpv4Prefix sets field value
func (o *Subnet) SetIpv4Prefix(v string) {
	o.Ipv4Prefix.Set(&v)
}

// GetIpv4BlockId returns the Ipv4BlockId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetIpv4BlockId() string {
	if o == nil || o.Ipv4BlockId.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ipv4BlockId.Get()
}

// GetIpv4BlockIdOk returns a tuple with the Ipv4BlockId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetIpv4BlockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipv4BlockId.Get(), o.Ipv4BlockId.IsSet()
}

// SetIpv4BlockId sets field value
func (o *Subnet) SetIpv4BlockId(v string) {
	o.Ipv4BlockId.Set(&v)
}

// GetIpv4Gateway returns the Ipv4Gateway field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetIpv4Gateway() string {
	if o == nil || o.Ipv4Gateway.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ipv4Gateway.Get()
}

// GetIpv4GatewayOk returns a tuple with the Ipv4Gateway field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetIpv4GatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipv4Gateway.Get(), o.Ipv4Gateway.IsSet()
}

// SetIpv4Gateway sets field value
func (o *Subnet) SetIpv4Gateway(v string) {
	o.Ipv4Gateway.Set(&v)
}

// GetIpv6Prefix returns the Ipv6Prefix field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetIpv6Prefix() string {
	if o == nil || o.Ipv6Prefix.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ipv6Prefix.Get()
}

// GetIpv6PrefixOk returns a tuple with the Ipv6Prefix field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetIpv6PrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipv6Prefix.Get(), o.Ipv6Prefix.IsSet()
}

// SetIpv6Prefix sets field value
func (o *Subnet) SetIpv6Prefix(v string) {
	o.Ipv6Prefix.Set(&v)
}

// GetIpv6BlockId returns the Ipv6BlockId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetIpv6BlockId() string {
	if o == nil || o.Ipv6BlockId.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ipv6BlockId.Get()
}

// GetIpv6BlockIdOk returns a tuple with the Ipv6BlockId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetIpv6BlockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipv6BlockId.Get(), o.Ipv6BlockId.IsSet()
}

// SetIpv6BlockId sets field value
func (o *Subnet) SetIpv6BlockId(v string) {
	o.Ipv6BlockId.Set(&v)
}

// GetIpv6Gateway returns the Ipv6Gateway field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetIpv6Gateway() string {
	if o == nil || o.Ipv6Gateway.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ipv6Gateway.Get()
}

// GetIpv6GatewayOk returns a tuple with the Ipv6Gateway field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetIpv6GatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipv6Gateway.Get(), o.Ipv6Gateway.IsSet()
}

// SetIpv6Gateway sets field value
func (o *Subnet) SetIpv6Gateway(v string) {
	o.Ipv6Gateway.Set(&v)
}

// GetMtu returns the Mtu field value if set, zero value otherwise.
func (o *Subnet) GetMtu() int32 {
	if o == nil || IsNil(o.Mtu) {
		var ret int32
		return ret
	}
	return *o.Mtu
}

// GetMtuOk returns a tuple with the Mtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subnet) GetMtuOk() (*int32, bool) {
	if o == nil || IsNil(o.Mtu) {
		return nil, false
	}
	return o.Mtu, true
}

// HasMtu returns a boolean if a field has been set.
func (o *Subnet) HasMtu() bool {
	if o != nil && !IsNil(o.Mtu) {
		return true
	}

	return false
}

// SetMtu gets a reference to the given int32 and assigns it to the Mtu field.
func (o *Subnet) SetMtu(v int32) {
	o.Mtu = &v
}

// GetPrefixLength returns the PrefixLength field value
func (o *Subnet) GetPrefixLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PrefixLength
}

// GetPrefixLengthOk returns a tuple with the PrefixLength field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetPrefixLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrefixLength, true
}

// SetPrefixLength sets field value
func (o *Subnet) SetPrefixLength(v int32) {
	o.PrefixLength = v
}

// GetRoutingType returns the RoutingType field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Subnet) GetRoutingType() string {
	if o == nil || o.RoutingType.Get() == nil {
		var ret string
		return ret
	}

	return *o.RoutingType.Get()
}

// GetRoutingTypeOk returns a tuple with the RoutingType field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetRoutingTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoutingType.Get(), o.RoutingType.IsSet()
}

// SetRoutingType sets field value
func (o *Subnet) SetRoutingType(v string) {
	o.RoutingType.Set(&v)
}

// GetStatus returns the Status field value
func (o *Subnet) GetStatus() SubnetStatus {
	if o == nil {
		var ret SubnetStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetStatusOk() (*SubnetStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Subnet) SetStatus(v SubnetStatus) {
	o.Status = v
}

// GetUsageStats returns the UsageStats field value if set, zero value otherwise.
func (o *Subnet) GetUsageStats() IpBlockUsageStats {
	if o == nil || IsNil(o.UsageStats) {
		var ret IpBlockUsageStats
		return ret
	}
	return *o.UsageStats
}

// GetUsageStatsOk returns a tuple with the UsageStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Subnet) GetUsageStatsOk() (*IpBlockUsageStats, bool) {
	if o == nil || IsNil(o.UsageStats) {
		return nil, false
	}
	return o.UsageStats, true
}

// HasUsageStats returns a boolean if a field has been set.
func (o *Subnet) HasUsageStats() bool {
	if o != nil && !IsNil(o.UsageStats) {
		return true
	}

	return false
}

// SetUsageStats gets a reference to the given IpBlockUsageStats and assigns it to the UsageStats field.
func (o *Subnet) SetUsageStats(v IpBlockUsageStats) {
	o.UsageStats = &v
}

// GetStatusHistory returns the StatusHistory field value
func (o *Subnet) GetStatusHistory() []StatusDetail {
	if o == nil {
		var ret []StatusDetail
		return ret
	}

	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusHistory, true
}

// SetStatusHistory sets field value
func (o *Subnet) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetCreated returns the Created field value
func (o *Subnet) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Subnet) SetCreated(v time.Time) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *Subnet) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *Subnet) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *Subnet) SetUpdated(v time.Time) {
	o.Updated = v
}

func (o Subnet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Subnet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["siteId"] = o.SiteId
	toSerialize["vpcId"] = o.VpcId
	toSerialize["subdomainId"] = o.SubdomainId.Get()
	toSerialize["controllerNetworkSegmentId"] = o.ControllerNetworkSegmentId.Get()
	toSerialize["ipv4Prefix"] = o.Ipv4Prefix.Get()
	toSerialize["ipv4BlockId"] = o.Ipv4BlockId.Get()
	toSerialize["ipv4Gateway"] = o.Ipv4Gateway.Get()
	toSerialize["ipv6Prefix"] = o.Ipv6Prefix.Get()
	toSerialize["ipv6BlockId"] = o.Ipv6BlockId.Get()
	toSerialize["ipv6Gateway"] = o.Ipv6Gateway.Get()
	if !IsNil(o.Mtu) {
		toSerialize["mtu"] = o.Mtu
	}
	toSerialize["prefixLength"] = o.PrefixLength
	toSerialize["routingType"] = o.RoutingType.Get()
	toSerialize["status"] = o.Status
	if !IsNil(o.UsageStats) {
		toSerialize["usageStats"] = o.UsageStats
	}
	toSerialize["statusHistory"] = o.StatusHistory
	toSerialize["created"] = o.Created
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

func (o *Subnet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"siteId",
		"vpcId",
		"subdomainId",
		"controllerNetworkSegmentId",
		"ipv4Prefix",
		"ipv4BlockId",
		"ipv4Gateway",
		"ipv6Prefix",
		"ipv6BlockId",
		"ipv6Gateway",
		"prefixLength",
		"routingType",
		"status",
		"statusHistory",
		"created",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	nullableRequiredProperties := map[string]struct{}{
		"description":                {},
		"subdomainId":                {},
		"controllerNetworkSegmentId": {},
		"ipv4Prefix":                 {},
		"ipv4BlockId":                {},
		"ipv4Gateway":                {},
		"ipv6Prefix":                 {},
		"ipv6BlockId":                {},
		"ipv6Gateway":                {},
		"routingType":                {},
	}
	for _, requiredProperty := range requiredProperties {
		_, nullable := nullableRequiredProperties[requiredProperty]
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubnet := _Subnet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSubnet)

	if err != nil {
		return err
	}

	*o = Subnet(varSubnet)

	return err
}

type NullableSubnet struct {
	value *Subnet
	isSet bool
}

func (v NullableSubnet) Get() *Subnet {
	return v.value
}

func (v *NullableSubnet) Set(val *Subnet) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnet) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnet(val *Subnet) *NullableSubnet {
	return &NullableSubnet{value: val, isSet: true}
}

func (v NullableSubnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
